useAnnotation: false
trialCommand: python main.py
trialCodeDirectory: /home/yanhuize/test/src/nni
trialGpuNumber: 1
trialConcurrency: 4
experimentName: ubiquant-3-7

searchSpaceFile: search_space.json
tuner:
  name: GridSearch
  # name: TPE
  # classArgs:
  #   optimize_mode: maximize
# assessor:
#     name: Medianstop
#     classArgs:
#       optimize_mode: minimize
#       start_step: 50

trainingService:
  platform: local
  useActiveGpu: true 